services:
  - type: web
    name: birthday-card
    env: docker
    plan: free
    repo: https://github.com/Muhammad-Ahmad12345/Birthday-card
    branch: main
    rootDir: "/"
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: MONGO_URI
        value: ""
      - key: DB_NAME
        value: "rubinaDB"